### ISSUE TITLE
Make `--list` output more user-friendly

### ISSUE THREAD

**Issue by dessert1** [heemayl/hat#1]
- [x] get rid of the brackets
- [x] re-organize the output, maybe in a table format with tab-separated columns and one job per line
- [x] make date and time human readable (www.xkcd.com/1179) – that's no joke actually, **please** follow ISO 8601!
- [x] make `use_shell` clear, I recommend to output `shell:none` if false and the content else

Here's an example how it could look like (I didn't count spaces!):

        job #     command         date and time           shell
        1         free            2018-01-03T20:03:10     none
        2         echo $PATH      2018-02-07T11:33:40     bash

**Comment by heemayl** [comment]
The output of `hatc -l` is actually a `json` dump from the Daemon, and it is shown *as-is*. The output format is something definitely worth checking. I'll take a look.

**Comment by heemayl** [comment]
All boxes checked:

```bash

% hatc -l
ID		    Time		Shell		Command
1	    2018-02-08T16:47:29		  -		free
2	    2018-02-09T14:40:30		bash		echo $PATH

```
