### ISSUE TITLE
New option `--exact`: Run command at specified time *only*.

### ISSUE THREAD

**Issue by dessert1** [heemayl/hat#3]
I suggest to add an option `--exact` that can be used in conjunction with `-a` and `-m` to mark a job as “exact”. Exact jobs should be executed at the specified time *only* rather than at any time later (e.g. if the machine sleeps at this time). The “exactness” of jobs should be shown by `-l` with maybe a special symbol before datetime (`--help` should explain that) *or* in a new row that's only displayed if necessary, i.e. at least one job is currently “exact”.

**Comment by heemayl** [comment]
Done! 

```bash
% hatc -h
...
  -e, --exact           Run the job only at the time specified, not after. By default, a job is will be run later if e.g. the computer was off at the desired run time.
...
```
