### ISSUE TITLE
--help output: quick option overview

### ISSUE THREAD

**Issue by dessert1** [heemayl/hat#5]
Currently, the examples and further information (e.g. on `datetime_spec`, which is relevant not only for `-a`) are thrown together, it's hard to get a quick overview which options `hatc` offers.

I suggest the following changes:
- [ ] Move all the examples to an own “Examples” section below.
- [ ] Move additional information to (an) own section(s) below – `datetime_spec` deserves being documented with at least a few sentences, even apart from the very helpful examples that are already existent. Info on files are usually (= on manpages) stored in a section called `FILES`.
- [ ] shorten the option lines of `-a`, `-m` and `-r`:

      -a <command> <datetime_spec> [<shell>], --add <command> <datetime_spec> [<shell>]
  would better be

      -a, --add <command> <datetime_spec> [<shell>]

**Comment by heemayl** [comment]
True. Eventually, a `man` page would be better suited IMO to dump all these. Will work on that.

**Comment by heemayl** [comment]
@dessert1 I hope the `hatc` man page covers it all now.
